server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
         # -----------------------
        # Microservicio Registrar Ganado
        # -----------------------
        - id: registrar-ganado-service
          uri: lb://registrar-ganado-service
          predicates:
            - Path=/api/ganado/**

        # -----------------------
        # Microservicio Registrar Lote
        # -----------------------
        - id: registrar-lote-service
          uri: lb://registrar-lote-service
          predicates:
            - Path=/api/lotes/**  