server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
    app:
      name: Registrar_ganado
      description: ok
      version: 1.0.0
    company:
      name: MyCompany
      contact:
      email: support@mycompany.com
      phone: +1234567890
    build:
      time: ${BUILD_TIME:2024-08-21T12:30:00Z}  


spring:
  cloud:
    discovery:
      enabled: true
